# Generated by Django 3.2.20 on 2023-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_parler_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='yum_rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Score de miam'),
            preserve_default=False,
        ),
    ]
