# Generated by Django 3.2.20 on 2023-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_parler_tests', '0002_food_yum_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Vegan'),
        ),
        migrations.AddField(
            model_name='food',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetarian'),
        ),
    ]
