# Generated by Django 5.2.7 on 2025-10-31 12:19

import django.db.models.deletion
import modelcluster.fields
import parler.fields
import parler.models
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_parler_tests", "0003_food_latest_revision_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FoodWithInlinePanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yum_rating",
                    models.PositiveSmallIntegerField(verbose_name="Score de miam"),
                ),
                (
                    "vegetarian",
                    models.BooleanField(default=False, verbose_name="Vegetarian"),
                ),
                ("vegan", models.BooleanField(default=False, verbose_name="Vegan")),
                ("slug", models.SlugField(verbose_name="Slug")),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nourriture - inline panel",
                "verbose_name_plural": "Nourritures - inline panel",
            },
            bases=(
                wagtail.models.preview.PreviewableMixin,
                parler.models.TranslatableModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="FoodWithInlinePanelTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("summary", models.TextField(verbose_name="Résumé")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "qa",
                    wagtail.fields.StreamField(
                        [("QaBlock", 1)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {"label": "Question"}),
                            1: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0)]],
                                {"label": "QA"},
                            ),
                        },
                        null=True,
                        verbose_name="Some QA",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="wagtail_parler_tests.foodwithinlinepanel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nourriture - inline panel Translation",
                "db_table": "wagtail_parler_tests_foodwithinlinepanel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FoodIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="wagtail_parler_tests.foodwithinlinepanel",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtail_parler_tests.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("food", "ingredient")},
            },
        ),
        migrations.CreateModel(
            name="IngredientTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="wagtail_parler_tests.ingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingredient Translation",
                "db_table": "wagtail_parler_tests_ingredient_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
