# Generated by Django 3.2.20 on 2023-08-01 17:17

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_parler_tests', '0006_foodwithedithandler_foodwithedithandlertranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWithSpecificEditHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yum_rating', models.PositiveSmallIntegerField(verbose_name='Score de miam')),
                ('vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('vegan', models.BooleanField(default=False, verbose_name='Vegan')),
            ],
            options={
                'verbose_name': 'Nourriture 4',
                'verbose_name_plural': 'Nourritures 4',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FoodWithSpecificEditHandlerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('summary', models.TextField(verbose_name='Résumé')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='wagtail_parler_tests.foodwithspecificedithandler')),
            ],
            options={
                'verbose_name': 'Nourriture 4 Translation',
                'db_table': 'wagtail_parler_tests_foodwithspecificedithandler_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
