# Generated by Django 3.2.20 on 2023-08-01 13:19

# Django imports
from django.db import migrations
from django.db import models
import django.db.models.deletion

# Third Party
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "yum_rating",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Score de miam"),
                ),
            ],
            options={
                "verbose_name": "Nourriture",
                "verbose_name_plural": "Nourritures",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FoodTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("summary", models.TextField(verbose_name="Résumé")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="wmp_tests.food",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nourriture Translation",
                "db_table": "wmp_tests_food_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
